repos:
  - repo: local
    hooks:
      - id: run_tests
        name: Run tests
        description: Run tests/test_rmfmt.py
        entry: ./tests/test_rmfmt.py
        language: system
        files: "^.*\\.py$"
  - repo: https://github.com/blag/rmfmt.git
    rev: 0.1.0
    hooks:
      - id: run_rmfmt
        name: Run rmfmt
        description: Run rmfmt on Python files
        entry: ./rmfmt.py
        language: system
        files: "^.*\\.py$"
